### PR TITLE
fix: remove bin field

### LINKED ISSUE #7: 🐛 Bug: Remove "bin" from package.json
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

No error in console when installing packages including this package.

### Actual

image

### Additional Info

Remove this line -
https://github.com/JoshuaKGoldberg/prettier-plugin-curly/blob/1c2616fa74762e55d3f95fb998804891d5f176ea/package.json#L15

### PR DESCRIPTION
**Pull request by so1ve**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Removes bin field

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks 😄

**Comment by JoshuaKGoldberg** [comment]
Should be available on npm in `prettier-plugin-curly@0.1.1`. Thanks!

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @joshuakgoldberg for maintenance.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by JoshuaKGoldberg** [comment]
...heh, looks like an auto-update fixed something.

**Comment by so1ve** [comment]
What happened o.0

**Pull request merged**
